// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_deletecam from "./routes/api/deletecam.ts";
import * as $api_deletewarnings from "./routes/api/deletewarnings.ts";
import * as $api_getcams from "./routes/api/getcams.ts";
import * as $api_getwarnings from "./routes/api/getwarnings.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $cameras_id_ from "./routes/cameras/[id].tsx";
import * as $detections from "./routes/detections.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $register from "./routes/register.tsx";
import * as $webcams from "./routes/webcams.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Logout from "./islands/Logout.tsx";
import * as $ReloadCams from "./islands/ReloadCams.tsx";
import * as $cameraslist from "./islands/cameraslist.tsx";
import * as $video from "./islands/video.tsx";
import * as $warninglist from "./islands/warninglist.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/deletecam.ts": $api_deletecam,
    "./routes/api/deletewarnings.ts": $api_deletewarnings,
    "./routes/api/getcams.ts": $api_getcams,
    "./routes/api/getwarnings.ts": $api_getwarnings,
    "./routes/api/joke.ts": $api_joke,
    "./routes/cameras/[id].tsx": $cameras_id_,
    "./routes/detections.tsx": $detections,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/register.tsx": $register,
    "./routes/webcams.tsx": $webcams,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Logout.tsx": $Logout,
    "./islands/ReloadCams.tsx": $ReloadCams,
    "./islands/cameraslist.tsx": $cameraslist,
    "./islands/video.tsx": $video,
    "./islands/warninglist.tsx": $warninglist,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
