<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.davidgonzase</groupId>
    <artifactId>wecamapp</artifactId>
    <version>1.0-SNAPSHOT</version>
    <repositories>
    <repository>
        <id>launch4j-repo</id>
        <url>https://launch4j.sourceforge.io/maven2/</url>
    </repository>
</repositories>

    <dependencies>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.79</version>
        </dependency>
        <dependency>
            <groupId>org.jcodec</groupId>
            <artifactId>jcodec</artifactId>
            <version>0.2.4</version>
        </dependency>
        <dependency>
            <groupId>dev.onvoid.webrtc</groupId>
            <artifactId>webrtc-java</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.9</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.9</version>
        </dependency>
        <dependency>
            <groupId>com.sparkjava</groupId>
            <artifactId>spark-core</artifactId>
            <version>2.9.4</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.70</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.davidgonzase.App</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>net.sf.launch4j</groupId>
                <artifactId>launch4j</artifactId>
                <version>3.50</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>launch4j</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jar>target/wecamapp-1.0-SNAPSHOT-jar-with-dependencies.jar</jar>
                    <outfile>target/wecamapp.exe</outfile>
                    <title>WebcamApp</title>
                    <headerType>console</headerType>
                    <jvmOptions>
                        <jvmOption>-Xms64m</jvmOption>
                        <jvmOption>-Xmx256m</jvmOption>
                    </jvmOptions>
                    <javaVersion>11</javaVersion>
                    <icon>src/main/resources/icono.ico</icon>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
